project:
  type: website

website:
  title: "A website on color scales"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Assignment1.qmd
        text: Viridis colors
      - href: Assignment1.qmd
        text: Terrain colors