project:
  type: website

website:
  title: "Assignment 1"
  navbar:
    left:
      - href: index.qmd
        text: Index
      - href: Prac_1.qmd
        text: Practical 1
      - href: Day3.qmd
        text: Day 3 Practical